{
 "title": "Kubernetes Application Observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Rate (1m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) or vector(0)",
     "legendFormat": "Requests / Sec"
    }
   ]
  },
  {
   "title": "Average Response Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m])) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage (Process)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) * 100 or vector(0)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory Usage (Process)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes) or vector(0)",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Kubernetes Container Logs Stream (Loki)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=\"log-monitoring-app\"}"
    }
   ]
  }
 ]
}